name: days_tracker
description: A privacy-first, offline Flutter app that tracks how many days the user spends in each country and city.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1

  # Dependency Injection
  get_it: ^9.2.0
  injectable: ^2.7.1

  # Code Generation (ONLY for BLoC events/states)
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  auto_route: ^11.1.0

  # Logging
  logger: ^2.0.2+1

  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.5
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  injectable_generator: ^2.4.1
  auto_route_generator: ^10.2.4

  # ─── Linting
  lint: ^2.8.0
  bloc_lint: ^0.3.6
  days_tracker_lint:
    path: packages/days_tracker_lint

dependency_overrides:
  custom_lint: 
    path: packages/custom_lint # wait for custom_lint to be updated to 0.8.2 to support analyzer 9.0.0

flutter:
  uses-material-design: true
  generate: true
