// Mocks generated by Mockito 5.4.6 from annotations
// in days_tracker/test/unit/usecases/calculate_visit_summary_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:days_tracker/domain/entities/location_ping.dart' as _i5;
import 'package:days_tracker/domain/entities/visit.dart' as _i4;
import 'package:days_tracker/domain/repositories/visits_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [VisitsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVisitsRepository extends _i1.Mock implements _i2.VisitsRepository {
  MockVisitsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Visit>> getAllVisits() => (super.noSuchMethod(
        Invocation.method(
          #getAllVisits,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Visit>>.value(<_i4.Visit>[]),
      ) as _i3.Future<List<_i4.Visit>>);

  @override
  _i3.Future<_i4.Visit?> getActiveVisit() => (super.noSuchMethod(
        Invocation.method(
          #getActiveVisit,
          [],
        ),
        returnValue: _i3.Future<_i4.Visit?>.value(),
      ) as _i3.Future<_i4.Visit?>);

  @override
  _i3.Future<void> createVisit(_i4.Visit? visit) => (super.noSuchMethod(
        Invocation.method(
          #createVisit,
          [visit],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateVisit(_i4.Visit? visit) => (super.noSuchMethod(
        Invocation.method(
          #updateVisit,
          [visit],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteVisit(String? visitId) => (super.noSuchMethod(
        Invocation.method(
          #deleteVisit,
          [visitId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> closeActiveVisit(DateTime? endDate) => (super.noSuchMethod(
        Invocation.method(
          #closeActiveVisit,
          [endDate],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Visit>> getVisitsInRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVisitsInRange,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue: _i3.Future<List<_i4.Visit>>.value(<_i4.Visit>[]),
      ) as _i3.Future<List<_i4.Visit>>);

  @override
  _i3.Future<void> addLocationPing(_i5.LocationPing? ping) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLocationPing,
          [ping],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.LocationPing>> getAllLocationPings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllLocationPings,
          [],
        ),
        returnValue:
            _i3.Future<List<_i5.LocationPing>>.value(<_i5.LocationPing>[]),
      ) as _i3.Future<List<_i5.LocationPing>>);

  @override
  _i3.Future<List<_i5.LocationPing>> getPendingGeocodingPings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingGeocodingPings,
          [],
        ),
        returnValue:
            _i3.Future<List<_i5.LocationPing>>.value(<_i5.LocationPing>[]),
      ) as _i3.Future<List<_i5.LocationPing>>);

  @override
  _i3.Future<void> updateLocationPing(_i5.LocationPing? ping) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocationPing,
          [ping],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAllData() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> exportData() => (super.noSuchMethod(
        Invocation.method(
          #exportData,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #exportData,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> importData(String? jsonData) => (super.noSuchMethod(
        Invocation.method(
          #importData,
          [jsonData],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
