name: days_tracker_lint
description: Custom lint rules for CreditKasa - bloc/cubit, widgets, architecture, and best practices.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  custom_lint_builder:
    git:
      url: https://github.com/invertase/dart_custom_lint.git
      path: packages/custom_lint_builder

dependency_overrides:
  custom_lint_core:
    git:
      url: https://github.com/invertase/dart_custom_lint.git
      path: packages/custom_lint_core
  custom_lint_analyzer_plugin_loader:
    git:
      url: https://github.com/invertase/dart_custom_lint.git
      path: packages/custom_lint/tools/analyzer_plugin
  custom_lint:
    path: ../custom_lint

dev_dependencies:
  test:
    ^1.24.0
