import 'package:days_tracker/domain/entities/country.dart';
import 'package:equatable/equatable.dart';

/// Domain entity representing a city.
///
/// Cities are associated with a country and store canonical coordinates
/// obtained from geocoding (city center point).
class City extends Equatable {
  /// Unique identifier (auto-generated by database).
  final int id;

  /// Foreign key to the parent country.
  final int countryId;

  /// English name of the city (e.g., "Warsaw", "Kyiv").
  final String cityName;

  /// Canonical latitude (city center from Google Maps).
  final double latitude;

  /// Canonical longitude (city center from Google Maps).
  final double longitude;

  /// Cached total days spent in this city.
  final int totalDays;

  /// Navigation property to the parent country (optional).
  final Country? country;

  const City({
    required this.id,
    required this.countryId,
    required this.cityName,
    required this.latitude,
    required this.longitude,
    this.totalDays = 0,
    this.country,
  });

  /// Creates a copy of this city with the given fields replaced.
  City copyWith({
    int? id,
    int? countryId,
    String? cityName,
    double? latitude,
    double? longitude,
    int? totalDays,
    Country? country,
    bool clearCountry = false,
  }) {
    return City(
      id: id ?? this.id,
      countryId: countryId ?? this.countryId,
      cityName: cityName ?? this.cityName,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
      totalDays: totalDays ?? this.totalDays,
      country: clearCountry ? null : (country ?? this.country),
    );
  }

  @override
  List<Object?> get props => [id, countryId, cityName, latitude, longitude, totalDays, country];

  @override
  String toString() {
    return 'City(id: $id, name: $cityName, countryId: $countryId, days: $totalDays)';
  }
}
