import 'package:equatable/equatable.dart';

/// Domain entity representing a country.
///
/// Countries are identified by their ISO 3166-1 alpha-2 code (e.g., "PL", "UA", "DE").
/// Each country tracks aggregate statistics like total days spent and visit dates.
class Country extends Equatable {
  /// Unique identifier (auto-generated by database).
  final int id;

  /// ISO 3166-1 alpha-2 country code (e.g., "PL", "UA").
  final String countryCode;

  /// English name of the country (e.g., "Poland", "Ukraine").
  final String countryName;

  /// Cached total days spent in this country.
  /// This is recalculated when visits are added/modified.
  final int totalDays;

  /// Date of the first recorded visit to this country.
  final DateTime? firstVisitDate;

  /// Date of the most recent visit to this country.
  final DateTime? lastVisitDate;

  const Country({
    required this.id,
    required this.countryCode,
    required this.countryName,
    this.totalDays = 0,
    this.firstVisitDate,
    this.lastVisitDate,
  });

  /// Creates a copy of this country with the given fields replaced.
  Country copyWith({
    int? id,
    String? countryCode,
    String? countryName,
    int? totalDays,
    DateTime? firstVisitDate,
    DateTime? lastVisitDate,
    bool clearFirstVisitDate = false,
    bool clearLastVisitDate = false,
  }) {
    return Country(
      id: id ?? this.id,
      countryCode: countryCode ?? this.countryCode,
      countryName: countryName ?? this.countryName,
      totalDays: totalDays ?? this.totalDays,
      firstVisitDate: clearFirstVisitDate ? null : (firstVisitDate ?? this.firstVisitDate),
      lastVisitDate: clearLastVisitDate ? null : (lastVisitDate ?? this.lastVisitDate),
    );
  }

  @override
  List<Object?> get props => [
    id,
    countryCode,
    countryName,
    totalDays,
    firstVisitDate,
    lastVisitDate,
  ];

  @override
  String toString() {
    return 'Country(id: $id, code: $countryCode, name: $countryName, days: $totalDays)';
  }
}
