import 'package:days_tracker/domain/entities/city.dart';
import 'package:days_tracker/domain/entities/country.dart';
import 'package:equatable/equatable.dart';

/// Domain entity representing presence in a city/country for a specific day.
///
/// This is a denormalized table for fast day counting. It's updated
/// whenever a location ping is processed.
class DailyPresence extends Equatable {
  /// Unique identifier (auto-generated by database).
  final int id;

  /// Associated visit ID.
  final String visitId;

  /// Date in YYYY-MM-DD format.
  final String date;

  /// City where user was present.
  final int cityId;

  /// Country where user was present.
  final int countryId;

  /// Number of pings recorded on this day.
  final int pingCount;

  /// Whether this meets the "any presence" counting rule (always true).
  final bool meetsAnyPresenceRule;

  /// Whether this meets the "two or more pings" counting rule.
  final bool meetsTwoOrMorePingsRule;

  /// Navigation property to city (optional).
  final City? city;

  /// Navigation property to country (optional).
  final Country? country;

  const DailyPresence({
    required this.id,
    required this.visitId,
    required this.date,
    required this.cityId,
    required this.countryId,
    this.pingCount = 1,
    this.meetsAnyPresenceRule = true,
    this.meetsTwoOrMorePingsRule = false,
    this.city,
    this.country,
  });

  /// Creates a copy of this daily presence with the given fields replaced.
  DailyPresence copyWith({
    int? id,
    String? visitId,
    String? date,
    int? cityId,
    int? countryId,
    int? pingCount,
    bool? meetsAnyPresenceRule,
    bool? meetsTwoOrMorePingsRule,
    City? city,
    Country? country,
    bool clearCity = false,
    bool clearCountry = false,
  }) {
    return DailyPresence(
      id: id ?? this.id,
      visitId: visitId ?? this.visitId,
      date: date ?? this.date,
      cityId: cityId ?? this.cityId,
      countryId: countryId ?? this.countryId,
      pingCount: pingCount ?? this.pingCount,
      meetsAnyPresenceRule: meetsAnyPresenceRule ?? this.meetsAnyPresenceRule,
      meetsTwoOrMorePingsRule: meetsTwoOrMorePingsRule ?? this.meetsTwoOrMorePingsRule,
      city: clearCity ? null : (city ?? this.city),
      country: clearCountry ? null : (country ?? this.country),
    );
  }

  @override
  List<Object?> get props => [
    id,
    visitId,
    date,
    cityId,
    countryId,
    pingCount,
    meetsAnyPresenceRule,
    meetsTwoOrMorePingsRule,
    city,
    country,
  ];

  @override
  String toString() {
    return 'DailyPresence(id: $id, date: $date, cityId: $cityId, pings: $pingCount)';
  }
}
